{{- if and .Values.database.enabled (not .Values.database.existingSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.databaseSecretName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}

